name: crux

services:
  api_service:
    container_name: crux_api_service
    build:
      context: api_service
    volumes:
      - ./api_service/:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint:
      ["python", "-m", "fastapi", "run", "api.py", "--port", "80", "--reload"]
    restart: unless-stopped

  backend:
    container_name: crux_backend
    build:
      context: backend
    ports:
      - 8080:80
    volumes:
      - ./backend/:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint:
      ["python", "-m", "fastapi", "run", "api.py", "--port", "80", "--reload"]
    restart: unless-stopped
    depends_on:
      - api_service

  frontend:
    container_name: crux_frontend
    build:
      context: frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    stdin_open: true
    tty: true
